logging:
  level:
    root: WARN
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: DEBUG


spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: xxxx
            client-secret: xxxx
