logging:
  level:
    root: WARN
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

server:
  error:
    whitelabel:
      enabled: false

spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: xxxx
            client-secret: xxxx
        provider:
          gitea:
            authorization-uri: https://gitea.com/login/oauth/authorize
            token-uri: https://gitea.com/login/oauth/access_token
            user-info-uri: https://gitea.com/api/v1/user
            user-name-attribute: username
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-name-attribute: login
